name:                processor
version:             0.1.0.0
github:              "githubuser/processor"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/processor#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- containers

library:
  source-dirs: src

executables:
  processor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Wno-safe
    - -Wno-prepositive-qualified-module
    - -Wno-implicit-prelude
    - -Wno-missing-safe-haskell-mode
    - -Wno-missing-import-lists
    - -Wno-missing-deriving-strategies
    - -Wno-all-missed-specialisations
    - -O2

tests:
  processor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - processor
